[project]
name = "sahi"
version = "0.11.20"
readme = "README.md"
description = "A vision library for performing sliced inference on large images/small objects"
requires-python = ">=3.8"
license = "MIT"
license-files = ["./LICENSE"]
dependencies = [
  "opencv-python<=4.10.0.84",
  "shapely>=2.0.0",
  "tqdm>=4.48.2",
  "pillow>=8.2.0",
  "pybboxes==0.1.6",
  "pyyaml",
  "fire",
  "terminaltables",
  "requests",
  "click",
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
homepage = "https://github.com/obss/sahi"

[project.scripts]
sahi = "sahi.cli:app"

[tool.uv]
dev-dependencies = [
  # "ultralytics",
  # "transformers",
  # "onnx",
  # "onnxruntime",
  # "yolov5",
  "pytest",
  "ruff",
  "pre-commit>=2.0",
  "pycocotools==2.0.6",
  "mmdet==3.0.0",
  "jupyterlab==3.0.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["modules"]

[tool.ruff]
line-length = 120
exclude = ["**/__init__.py", ".git", "__pycache__", "*.ipynb"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["--import-mode=importlib", "--no-header"]
pythonpath = ["."]
